name: Gatsby Blog

on: [repository_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

     # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
      env:
        CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
        CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
        API_KEY: ${{secrets.API_KEY}}
        AUTH_DOMAIN: ${{secrets.AUTH_DOMAIN}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        PROJECT_ID: ${{secrets.PROJECT_ID}}
        STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
        MESSAGING_SENDER_ID: ${{secrets.MESSAGING_SENDER_ID}}
        APP_ID: ${{secrets.APP_ID}}
    
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy
      run: surge ./public thegatsbyblog.surge.sh/ --token ${{secrets.SURGE_TOKEN}}      
