name: Gatsby Blog

on: [repository_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

     # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
      env:
        CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
        CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
        GATSBY_API_KEY: ${{secrets.GATSBY_API_KEY}}
        GATSBY_AUTH_DOMAIN: ${{secrets.GATSBY_AUTH_DOMAIN}}
        GATSBY_DATABASE_URL: ${{secrets.GATSBY_DATABASE_URL}}
        GATSBY_PROJECT_ID: ${{secrets.GATSBY_PROJECT_ID}}
        GATSBY_STORAGE_BUCKET: ${{secrets.GATSBY_STORAGE_BUCKET}}
        GATSBY_MESSAGING_SENDER_ID: ${{secrets.GATSBY_MESSAGING_SENDER_ID}}
        GATSBY_APP_ID: ${{secrets.GATSBY_APP_ID}}
    
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy
      run: surge ./public thegatsbyblog.surge.sh/ --token ${{secrets.SURGE_TOKEN}}      
